name: onlyoffice-desktopeditors
version: "4.8.7"
summary: "An office suite that allowing to create, view and edit local documents."
description: "ONLYOFFICE Desktop Editors is a free office suite that combines text, spreadsheet and presentation editors allowing to create, view and edit documents stored on your Windows/Linux PC or Mac without an Internet connection. It is fully compatible with Office Open XML formats: .docx, .xlsx, .pptx."
grade: stable
confinement: strict
icon: icons/asc-de-256.png

apps:
  onlyoffice-desktopeditors:
    command: usr/bin/desktopeditors
    desktop: usr/share/applications/desktopeditors.desktop
    plugs:
      - home
      - network
      - desktop
      - x11
      - locale-control
      - opengl
      - unity7
      - cups-control
      - gsettings
      - browser-support

parts:
  onlyoffice-desktopeditors:
    plugin: dump
    source: http://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb
    source-type: deb
    stage-packages:
      - on amd64:
        - fonts-crosextra-carlito
        - fonts-dejavu
        - fonts-liberation
        - fonts-opensymbol
        - fonts-takao-gothic
        - gsettings-desktop-schemas
        - gsettings-ubuntu-schemas
        - libatk-adaptor
        - libc6
        - libcairo2
        - libcanberra-gtk-module
        - libcomerr2
        - libcurl3
        - libgail-3-0
        - libgcc1
        - libgconf-2-4
        - libgcrypt20
        - libgl1-mesa-dri
        - libgpg-error0
        - libgsettings-qt1
        - libgtkglext1
        - liblzma5
        - libnss3
        - libpcre3
        - libselinux1
        - libstdc++6
        - libsystemd0
        - libuuid1
        - libxml2
        - libxss1
        - locales-all
        - overlay-scrollbar-gtk2
        - packagekit-gtk3-module
        - ttf-mscorefonts-installer
        - unity-gtk2-module
        - x11-common
        - zlib1g
      - else fail
    install: |
      mv $SNAPCRAFT_PART_INSTALL/usr/bin/desktopeditors $SNAPCRAFT_PART_INSTALL/usr/bin/desktopeditors-old &&
      sed 's|asc-de|\${SNAP}/opt/onlyoffice/desktopeditors/asc-de-256.png|g' -i $SNAPCRAFT_PART_INSTALL/usr/share/applications/desktopeditors.desktop

#    install: |
#      mv $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t.bin

  starter:
    plugin: dump
    source: ./bin/
    organize:
      run-desktopeditors.sh: usr/bin/desktopeditors
#      x2t.sh: $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t
